name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: |
        A clear and concise description of the feature.
        If this requires a new utility or API change,
        a Changeset will be required in the implementation PR.
      placeholder: What would you like to see?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: I think it should work like...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
      placeholder: I also thought about...
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package would this affect?
      options:
        - "@commerce-atoms/cart"
        - "@commerce-atoms/date"
        - "@commerce-atoms/discounts"
        - "@commerce-atoms/filters"
        - "@commerce-atoms/metafield"
        - "@commerce-atoms/money"
        - "@commerce-atoms/pagination"
        - "@commerce-atoms/seo"
        - "@commerce-atoms/urlstate"
        - "@commerce-atoms/variants"
        - "New package"
        - "Multiple packages"
        - "Unknown"
    validations:
      required: true
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the documentation
          required: true
        - label: This aligns with Shoppy's philosophy (pure utilities, no UI, framework-agnostic)
          required: true

